// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKyhU_vhIGOHO2jeVF0VUzK1ZYGVFvz9Q',
    appId: '1:799717436277:web:4504dd3ac4fe7e979fc13c',
    messagingSenderId: '799717436277',
    projectId: 'sunnah-steps-82d64',
    authDomain: 'sunnah-steps-82d64.firebaseapp.com',
    storageBucket: 'sunnah-steps-82d64.firebasestorage.app',
    measurementId: 'G-515ZW7FDP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6q1pqo4FfaOIq-dRJGJO3bv7sM7PsRm8',
    appId: '1:799717436277:android:e82cb357d50c47329fc13c',
    messagingSenderId: '799717436277',
    projectId: 'sunnah-steps-82d64',
    storageBucket: 'sunnah-steps-82d64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQe9KgFhYLzb-EPWoPzJPPwwCI9BQPtWo',
    appId: '1:799717436277:ios:a43cf5b3dbb47c179fc13c',
    messagingSenderId: '799717436277',
    projectId: 'sunnah-steps-82d64',
    storageBucket: 'sunnah-steps-82d64.firebasestorage.app',
    iosClientId: '799717436277-5lep5cfjkr526kd2efva30bkqfmp2n6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.sunnahSteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQe9KgFhYLzb-EPWoPzJPPwwCI9BQPtWo',
    appId: '1:799717436277:ios:a43cf5b3dbb47c179fc13c',
    messagingSenderId: '799717436277',
    projectId: 'sunnah-steps-82d64',
    storageBucket: 'sunnah-steps-82d64.firebasestorage.app',
    iosClientId: '799717436277-5lep5cfjkr526kd2efva30bkqfmp2n6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.sunnahSteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKyhU_vhIGOHO2jeVF0VUzK1ZYGVFvz9Q',
    appId: '1:799717436277:web:fd7f87c5b00be0e59fc13c',
    messagingSenderId: '799717436277',
    projectId: 'sunnah-steps-82d64',
    authDomain: 'sunnah-steps-82d64.firebaseapp.com',
    storageBucket: 'sunnah-steps-82d64.firebasestorage.app',
    measurementId: 'G-H7640QZCV3',
  );
}
